### ISSUE TITLE
Roadmap for WatchTower

### ISSUE THREAD

**Issue by Enigmazflo** [DefineX-Studios/WatchTower#10]
- [x] #2 
- [x] #3 
- [x] #1 
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #11
- [x] #7 
- [x] #8 
- [x] create roadmap for frontend
- [ ] [WIP] using Heartbeat to make the service more stable
- [ ] #9 
- [ ] #12 
- [x] #13
- [x] #14 
- [ ] #15 
- [x] Export to SSH server

BUGS
- [ ] [WIP] API calls not working on windows after format fixing
- [ ] [WIP] WSL not working, unable to test.. will check on mac instead

GUI
- [ ] https://github.com/DefineX-Studios/WatchTower-GUI/issues/10
